-- Insert mock order items (menu item ID, order ID, quantity, customization info) expanded
INSERT INTO order_items (menu_item_id, order_id, quantity, customization_info) VALUES
(1, 1, 2, 'Extra foam'),
(2, 2, 1, 'No sugar'),
(3, 3, 3, 'With almond milk'),
(1, 4, 1, 'With extra shot'),
(2, 5, 2, 'No blueberries'),
(1, 6, 3, 'Light foam'),
(3, 7, 2, 'With skim milk'),
(1, 8, 1, 'Extra hot'),
(3, 9, 1, 'With extra shot'),
(2, 10, 2, 'No sugar, extra butter'),
(1, 11, 1, 'No foam'),
(3, 12, 1, 'With oat milk'),
(6, 13, 1, 'Hotter than usual'),
(7, 14, 2, 'Extra cream'),
(8, 15, 1, 'No nuts'),
(1, 16, 2, 'Less foam'),
(3, 17, 2, 'With extra vanilla'),
(2, 18, 1, 'More blueberries'),
(7, 19, 1, 'Extra hot'),
(8, 20, 3, 'With extra sugar'),
(5, 21, 1, 'No frosting'),
(3, 22, 2, 'With coconut milk'),
(2, 23, 1, 'No sugar, extra honey'),
(6, 24, 2, 'With extra soy milk');